### PR TITLE
Use module paths instead of conditional module includes for sys modules

### PR DESCRIPTION
**Pull request by joshka**
Saves 1 LOC

### CODE REVIEW

**Comment by joshka** [comment]
Hrm, this one seems to be trigger a lot of build failures. Maybe too many to worry about a single LOC :D

**Comment by ilai-deutel** [comment]
This is a great idea, and regardless of line count it also looks cleaner. I don't understand why the dead code warnings appear though, and only on Windows not Linux or Mac.

I don't know if it's an issue with the code or with the compiler, I may do some more testing with a Windows machine later :)

**Comment by ilai-deutel** [comment]
I just figured it out, I think the `#[cfg(windows)] mod windows;` line needs to be removed

**Comment by ilai-deutel** [comment]
FYI, I reported the misleading warning: https://github.com/rust-lang/rust/issues/133197

**Pull request merged**
